%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Program: 11_basic_course_on_R_testing1_practical.rnw                    %
% Purpose: Provide an introduction to R for the MGC R Basic R course      %
% Prerequisite(s): none                                                   %
% Author: Elizazbeth Ribble                                               %
% Created: c. april 2013                                                  %
% Last update: 2019-05-05                                                 %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% begin preamble %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[12pt]{article}

\usepackage{amsmath}
\usepackage{hyperref}
\usepackage[authoryear,round]{natbib}
\usepackage{graphicx}
\usepackage{enumerate}

\textwidth=6.2in
\textheight=8.5in
%\parskip=.3cm
\oddsidemargin=.1in
\evensidemargin=.1in
\headheight=-.3in

\newcommand{\scscst}{\scriptscriptstyle}
\newcommand{\scst}{\scriptstyle}
\author{Elizabeth Ribble\footnote{emcclel3@msudenver.edu}}
\date{28 Oct - 1 Nov 2019}

\begin{document}

\title{Basic Course on {\tt R}:\\
       Hypothesis Testing and Confidence Intervals 1\\
       Practical}
\maketitle
\tableofcontents
\newpage\section{Baby Data}
\begin{enumerate}[{1.}]
  \item Read in the data ``R\_data\_January2015.csv'' with a header and row names from the first column. Assign it to the object {\tt babydata} and allow strings be converted to factors. Attach the data to the environment.
%  <<>>=
%  babydata <- read.csv("R_data_January2015.csv",header=T,row.names=1)
%  attach(babydata)
%  @
  \vspace{10 mm}
  
  \item What are the dimensions of {\tt babydata}? What is the class? Answer these questions separately with two functions and then together with one function.
%  <<>>=
%  dim(babydata)
%  class(babydata)
%  str(babydata)
%  @
  \vspace{10 mm}
  
  \item Answer the following questions pertaining to the variable {\tt SAH}:
    \begin{enumerate}
      \item What are the 20\% quantiles of {\tt SAH}?
%  <<>>=
%  quantile(SAH,seq(0,1,.2))
%  @
      \vspace{10 mm}
      \item What are the mean, median, variance and standard deviation of {\tt SAH}?
%  <<>>=
%  summary(SAH)
%  ## or
%  mean(SAH)
%  median(SAH)
%  vs <- var(SAH)
%  sqrt(vs)
%  @
      \vspace{10 mm}
      \item Create a stem and leaf plot of {\tt SAH}. 
%  <<>>=
%  stem(SAH)
%  @
      \vspace{10 mm}
      \item Create a histogram and a horizontal boxplot of {\tt SAH} in one graphics window where the plot of the histogram is above the boxplot. 
%  \begin{center}  
%  <<fig=TRUE>>=
%  par(mfrow=c(2,1))
%  hist(SAH)
%  boxplot(SAH,horizontal=TRUE)
%  @
%  \end{center}
      \vspace{10 mm}
      \item Utilize all 3 graphs to describe the shape of the distribution of {\tt SAH}. 
% The distribution is unimodal and slightly skewed to the right.
      \vspace{10 mm}
      \item Log-transform SAH (assign it to {\tt logSAH}).
%  <<>>=
%  logSAH <- log(SAH)
%  @
      \vspace{10 mm}
      \item What are the 20\% quantiles of {\tt logSAH}?
%  <<>>=
%  quantile(logSAH,seq(0,1,.2))
%  @
      \vspace{10 mm}
      \item What are the mean, median, variance and standard deviation of {\tt logSAH}?
%  <<>>=
%  summary(logSAH)
%  ## or
%  mean(logSAH)
%  median(logSAH)
%  vls <- var(logSAH)
%  sqrt(vls)
%  @
      \vspace{10 mm}
      \item Create a stem and leaf plot of {\tt logSAH}. 
%  <<>>=
%  stem(SAH)
%  @
      \vspace{10 mm}
      \item Create a histogram and a horizontal boxplot of {\tt logSAH} in one graphics window where the plot of the histogram above the boxplot. 
%  \begin{center}  
%  <<fig=TRUE>>=
%  par(mfrow=c(2,1))
%  hist(SAH)
%  boxplot(SAH,horizontal=TRUE)
%  @
%  \end{center}  
      \vspace{10 mm}
      \item Utilize all 3 graphs to describe the shape of the distribution of {\tt logSAH}. 
% The distribution is unimodal, symmetric and appears normal. 
      \vspace{10 mm}
      \item What did the log transformation do to the values of {\tt SAH}? 
% Dampened the effect of skewness to make the distribution more normal and symmetric.
      \vspace{10 mm}
      \item Take a random sample of size 50 from {\tt logSAH} and make a histogram. Does this distribution have a similar shape compared to that of all {\tt logSAH} values?
%  \begin{center}  
%  <<fig=TRUE>>=
%  hist(sample(logSAH, 50))
%  @
%  \end{center}   
      \vspace{10 mm}
      \item Take a random sample of size 50 with replacement from {\tt logSAH} and make a histogram. Does this distribution have a similar shape compared to that of all {\tt logSAH} values?
%  \begin{center}  
%  <<fig=TRUE>>=
%  hist(sample(logSAH, 50, replace=T))
%  @
%  \end{center}  
  \end{enumerate}
  \vspace{10 mm}
  
  \item Answer the following questions pertaining to the variable {\tt medication}: 
    \begin{enumerate}
      \item Use a function to create frequency table of the number of mothers taking medication and not taking medication.
%  <<>>=
%  table(medication)
%  @
      \vspace{10 mm}
      \item Calculate the percent of the mothers who are taking medication; what is the percentage?
%  <<>>=
%  table(medication)/length(medication)
%  @   
    \end{enumerate}
  \vspace{10 mm}
  
  \item Answer the following questions pertaining to the variable {\tt educational\_level}: 
    \begin{enumerate}
      \item Create a frequency table of the number of mothers in each education level.
      \vspace{10 mm}
      \item Create a horizontal boxplot of the {\tt SAH} values for the different levels of education and color each box a different color. Add a rug plot of the values where the ticks for each group have the same color as their corresponding box. 
%  \begin{center}
%  <<fig=TRUE>>=
%  boxplot(triglycerides ~ educational_level, horizontal=TRUE, col=c("purple","orange","green"))
%  rug(triglycerides[educational_level=="low"], col="green")
%  rug(triglycerides[educational_level=="intermediate"], col="orange")
%  rug(triglycerides[educational_level=="high"], col="purple")
%  @
%  \end{center}
      \vspace{15 mm}
      \item Are {\tt triglycerides} normally distributed (make a plot to answer this question)? If not, log-transform them. Are the log-transformed values normal? 
%  \begin{center}
%  <<fig=TRUE>>=
%  par(mfrow=c(1,2))
%  hist(triglycerides)
%  hist(log(triglycerides))
%  @
%  \end{center}
% The values are skewed to the right and are still skewed after a log transformation.       
      \vspace{15 mm}
      \item Is the average triglyceride level for highly educated mothers different from that of mothers with a low education level? Formulate a hypothesis, test it, and make a decision about whether or not you can reject the null hypothesis. Can you use a $t$-test (either on the raw or log-transformed data)? Why or why not (hint: how are the data distributed)? 
% We cannot use the $t$-test because the data are not normally distributed, even after a log transformation! However, since the shapes of the distributions are similar, as evidence by the below plot, we can perform a Wilcoxon Rank Sum test. 
%  \begin{center}
%  <<fig=TRUE>>=
%  trigly_high <- triglycerides[educational_level=="high"]
%  trigly_low <- triglycerides[educational_level=="low"]
%  par(mfrow=c(1,2))
%  hist(trigly_high, main = "high")
%  hist(trigly_low, main = "low")
%  @
%  \end{center}
% Our null hypothesis is that the difference in location between the low and high education levels is 0. The alternative hypothesis is that there is a difference. 
%  <<>>=
%  wilcox.test(trigly_high, trigly_low)
%  @
% The $p$-value is not less than 0.05 so we fail to reject the null and conclude that we do not have enough evidence to show a statistically significant difference between the centers of the high and low mothers' triglycerides.
      \vspace{90 mm}
      \item Now re-do the test and make your decision to reject/not reject the null based on the confidence interval. Challenge: instead of just looking at the output, extract the confidence interval from the test output and use logical operators to answer the question of whether the interval contains the null value. 
%  <<>>=
%  wtest <- wilcox.test(trigly_high, trigly_low, conf.int=TRUE)
%  ciw <- wtest$conf.int
%  0 > ciw[1] & 0 < ciw[2]
%  @
% Since the confidence interval contains 0, we fail to reject the null.   
    \end{enumerate}
      \vspace{30 mm}
  
  \newpage\item Answer the following questions pertaining to the variable {\tt Status}:
    \begin{enumerate}
      \item Are the average {\tt SAH} values for the two levels of {\tt Status} (normal brain development or intellectual disability) different? Formulate a hypothesis, test it, and make a decision about whether or not you can reject the null hyopthesis. Can you use a $t$-test (either on the raw or log-transformed data)? Why or why not (hint: check distributions with plots)? 
% We can use the $t$-test on the log-transformed data, since they are normally distributed, as shown in the plots below.
%  \begin{center}
%  <<fig=TRUE>>=
%  sah_m <- SAH[Status=="intellectual disability"]
%  sah_n <- SAH[Status=="normal brain development"]
%  par(mfrow=c(2,2))
%  hist(sah_m, main = "intellectual disability")
%  hist(sah_n, main = "normal brain development")
%  hist(log(sah_m), main = "intellectual disability")
%  hist(log(sah_n), main = "normal brain development")
%  @
%  \end{center}
% Our null hypothesis is that the difference in mean {\tt SAH} between the two groups is 0. The alternative hypothesis is that there is a difference in means. 
%  <<>>=
%  sstest <- t.test(log(SAH)~Status)
%  sstest
%  sstest$p.value
%  sstest$conf.int
%  @
% The $p$-value is less than 0.05 (and 0 is not in the CI) so we can reject the null hypothesis that the difference in means between the two groups is 0. We conclude that there is a statistically significant difference between the average log-{\tt SAH} of mother's with mentally retarded children and the average log-{\tt SAH} of those women whose children have normal brain development. 
      \vspace{90 mm}
      \item What is the fold change of log-{\tt SAH} between the 2 groups? Calculate it two ways: use the output from the previous test and also use the data itself (function {\tt mean} plus logical operators). 
%  <<>>=
%  sstest$estimate[2]/sstest$estimate[1]
%  mean(log(SAH)[Status=="normal brain development"])/mean(log(SAH)[Status=="intellectual disability"])
%  @
      \vspace{25 mm}
      \item Make a boxplot of the {\tt SAH} values of the 2 groups and calculate the fold change of {\tt SAH} between the 2 groups. Does the difference seem clinically relevant? Why or why not? 
%  begin{center}
%  <<fig=TRUE>>=
%  mean(SAH[Status=="normal brain development"])/mean(SAH[Status=="intellectual disability"])
%  @
%  end{center}
% The fold change is really close to one and there is actually quite a bit of overlap in the boxplots. The statistically significant difference of the log-transformed data is quite subtle and may not be relevant, though further investigation of confounding factors may elucidate the true relationship between {\tt SAH} and brain development. 
    \end{enumerate}

\end{enumerate}



\end{document}
